"""add_endpoint_url_to_agents

Revision ID: 2d3717473392
Revises: f3f063a558e2
Create Date: 2026-04-20 16:58:41.750955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d3717473392'
down_revision: Union[str, None] = 'f3f063a558e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('endpoint_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'endpoint_url')
    # ### end Alembic commands ###
