"""add_endpoint_protocol_to_agents

Revision ID: 88e5ee7ff6b9
Revises: 91173bff61e2
Create Date: 2026-04-22 17:17:21.877352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88e5ee7ff6b9'
down_revision: Union[str, None] = '91173bff61e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('endpoint_protocol', sa.String(length=20), server_default='openai', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'endpoint_protocol')
    # ### end Alembic commands ###
