"""add winning_attempt_id to tasks

Revision ID: 91173bff61e2
Revises: 191cfeb966ca
Create Date: 2026-04-21 20:17:52.666222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91173bff61e2'
down_revision: Union[str, None] = '191cfeb966ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('winning_attempt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_attempts', ['winning_attempt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'winning_attempt_id')
    # ### end Alembic commands ###
