"""add endpoint_api_key to agents

Revision ID: 93dbfd21e749
Revises: 2d3717473392
Create Date: 2026-04-20 18:36:45.307066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93dbfd21e749'
down_revision: Union[str, None] = '2d3717473392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('endpoint_api_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'endpoint_api_key')
    # ### end Alembic commands ###
