"""add_encrypted_key_to_api_keys

Revision ID: c33ddf4364a7
Revises: 93dbfd21e749
Create Date: 2026-04-21 17:17:34.056626
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c33ddf4364a7'
down_revision: Union[str, None] = '93dbfd21e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('encrypted_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'encrypted_key')
    # ### end Alembic commands ###
